[tool.poetry]
name = "10_0_0_55"
version = "2.0.1"
description = "A headless login / logout script for 10.0.0.55"
authors = ["spencerwooo <spencer.woo@outlook.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
