[tool.poetry]
name = "bitsrun"
version = "3.2.0"
description = "A headless login / logout script for 10.0.0.55"
authors = ["spencerwooo <spencer.woo@outlook.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7,<4"
requests = "^2.28.1"
click = "^8.1.3"
platformdirs = "^2.6.2"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
ruff = "^0.0.198"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
bitsrun = "bitsrun.cli:cli"
